[routing]
[[routing.mint_config_list]]
mint = "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump"
pump_pool_list = [
 "AmmpSnW5xVeKHTAU9fMjyKEMPgrzmUj3ah5vgvHhAB5J",
]
meteora_dlmm_pool_list = [
 "6wJ7W3oHj7ex6MVFp2o26NSof3aey7U8Brs8E371WCXA",
 "4Dvr3ghgphp4aTAsB34fmPP9Uk6e6xui6PbPaNiAHqRo",
]
#raydium_pool_list = [
#  "example_address",
#]
#raydium_cp_pool_list = [
#  "example_address",
#]
lookup_table_accounts = [
  "4sKLJ1Qoudh8PJyqBeuKocYdsZvxTcRShUt9aKqwhgvC",
  "8mRar7rLwwuM4Nx8fJaAoLBgUMXNMggyLJGsYtxvbbLR",
]
process_delay = 400


[rpc]
url = "http://5.39.216.200:8899"

[spam]
enabled = true
sending_rpc_urls = [
  "http://rpc-ams.thornode.io",
]
compute_unit_price = { strategy = "Random", from = 28311, to = 488111, count = 1 }
skip_preflight = true

[jito]
enabled = false
block_engine_urls = [
  "https://ny.mainnet.block-engine.jito.wtf/api/v1",
  "https://slc.mainnet.block-engine.jito.wtf/api/v1",
  "https://amsterdam.mainnet.block-engine.jito.wtf/api/v1",
  "https://london.mainnet.block-engine.jito.wtf/api/v1",
  "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1",
  "https://mainnet.block-engine.jito.wtf/api/v1",
]
# ip_addresses = ["156.229.120.0/24"]
min_profit = 17000
use_separate_tip_account = true

[jito.tip_config]
strategy = "Random"
from = 6000
to = 500500
count = 4

[kamino_flashloan]
enabled = false

[bot]
base_mint = "So11111111111111111111111111111111111111112" # Optional, default to SOL
compute_unit_limit = 438_000
merge_mints = false

[wallet]
